homeassistant:
  packages:
    v2g_pack: !include packages/v2g_liberty/v2g_liberty_package.yaml

# Loads default set of integrations. Do not remove.
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
