#!/usr/bin/bash -x

# Stop on errors
set -e

cd "$(dirname "$0")/../.devcontainer"

# Do not overwrite existing config
if [ -e config/.ready ]; then exit 0; fi

if [ ! -x config ]; then mkdir config; fi
rm -rf config/.* config/*
cp -avR init-config/.* init-config/* config

# Signal we are done copying
touch config/.ready
