###############################
#        Settings tab         #
###############################
# To be included in the v2g_liberty_dashboard.yaml
- type: grid
  cards:
    - type: custom:v2g-liberty-ping-card
    - type: custom:v2g-liberty-optimisation-settings-card
      layout_options:
        grid_columns: full
    - type: custom:v2g-liberty-charger-settings-card
      layout_options:
        grid_columns: full

- type: grid
  cards:
    - type: custom:v2g-liberty-car-settings-card
      layout_options:
        grid_columns: full
    - type: custom:v2g-liberty-car-reservation-calendar-settings-card
      layout_options:
        grid_columns: full
    - type: custom:v2g-liberty-administrator-settings-card
      layout_options:
        grid_columns: full

- type: grid
  cards:
    - type: custom:v2g-liberty-electricity-contract-settings-card
      layout_options:
        grid_columns: full
    - type: custom:v2g-liberty-schedule-settings-card
      layout_options:
        grid_columns: full
    - type: entities
      entities:
        - type: button
          name: " "
          action_name: 🔄 Restart V2G Liberty ››
          tap_action:
            action: call-service
            confirmation:
              text: Restart Home Assistant and the V2G Liberty Add-on now? If you made any manual changes to the Home Assistant configuration make sure to check if it is valid.
            service: script.restart_ha
            target: {}
        - type: button
          name: " "
          action_name: 🛑 Stop V2G Liberty ››
          tap_action:
            action: call-service
            confirmation:
              text: The only way to stop V2G Liberty is to stop the add-on. Goto Settings -> Add-ons -> V2G Liberty -> Stop
            service: script.stop_v2g_liberty
            target: {}
        - type: button
          name: " "
          action_name: 🏭 Reset to factory defaults ››
          tap_action:
            action: call-service
            confirmation:
              text: Are you sure you want to reset the settings to the factory defaults? This cannot be undone. Home Assistant will restart, this may take a few minutes.
            service: script.reset_to_factory_defaults
            target: {}
      card_mod:
        style: |
          ha-card {
            border: none;
            margin: 0;
            padding: 0;
            background-color: transparent;
          }

    - type: markdown
      # Here just for triggering of rendering, no content.
      content: " "
      card_mod:
        style: |
          ha-card {
            display: none;
          }
