################################################################################
#                                                                              #
#    V2G Liberty Package                                                       #
#    Contains all entities needed for the V2G Liberty software to work         #
#                                                                              #
################################################################################

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      filename: packages/v2g_liberty/v2g_liberty_dashboard.yaml
      title: V2G Liberty
      icon: mdi:car-electric
      show_in_sidebar: true
      require_admin: false

frontend:
  extra_module_url:
    - /local/v2g_liberty/lovelace-card-mod/card-mod.js
    - /local/v2g_liberty/apexcharts-card/apexcharts-card-v2-1-2.js


input_select:
  gb_dno_region:
    name: Great Britain DNO region
    icon: mdi:home-map-marker
    options:
      - Eastern England
      - East Midlands
      - London
      - Merseyside and Northern Wales
      - West Midlands
      - North Eastern England
      - North Western England
      - Southern England
      - South Eastern England
      - Southern Wales
      - South Western England
      - Yorkshire
      - Southern Scotland
      - Northern Scotland

  # Options will be set through v2g_globals
  fm_asset:
    name: FlexMeasures asset
    icon: mdi:format-list-bulleted-type
    options:
      - Please choose an option

  # Options will be set through v2g_globals
  admin_mobile_name:
    name: The mobile of the administrator
    icon: mdi:shield-account
    options:
      - Please choose an option
  admin_mobile_platform:
    name: The operation system of the mobile of the administrator
    icon: mdi:cellphone-cog
    options:
      - android
      - ios

  car_calendar_source:
    name: Source for car calendar
    icon: mdi:sprout
    options:
      - Direct caldav source
      - Home Assistant integration

  # Used when the car calendar is provided by a local integration (e.g. Google Calendar)
  integration_calendar_entity_name:
    name: Calendar integration
    icon: mdi:calendar-edit-outline
    options:
      - Please choose an option

  # Used when the car calendar is online
  car_calendar_name:
    name: Car reservation calendar
    icon: mdi:car-info
    options:
      - Please choose an option

  electricity_provider:
    options:
      - nl_generic
      - nl_anwb_energie
      - nl_greenchoice
      - nl_next_energy
      - nl_tibber
      - no_generic
      - gb_octopus_energy
      - au_amber_electric

  optimisation_mode:
    options:
      - price
      - emission

  charge_mode:
    name: Charge mode
    options:
      - Automatic
      - Max boost now
      - Stop
    # "Stop" used to be "Off" but this triggers HA to see it as False..
    icon: mdi:battery-charging-medium

input_boolean:
  # Settings related entities
  use_reduced_max_charge_power:
    name: Change default (dis-)charge power
    icon: mdi:square-edit-outline

  fm_show_option_to_change_url:
    name: Change default server
  use_vat_and_markup:
    name: Use VAT and markup to calculate price in HA

  # Used for signaling in the UI that the EPEX prices temporarily cannot be retrieved from FM
  error_epex_prices_cannot_be_retrieved:
    name: "Error: EPEX prices cannot be retrieved"

  # Used for signaling in the UI there are no new (valid) schedules available.
  # E..g. no communication with FM, timeouts, flatline, etc.
  error_no_new_schedule_available:
    name: "Error: No new schedule available"

  # Used for signaling in the UI that Modbus communication with the charger is no longer possible
  # This usually indicates the Modbus Module in the charger has crashed and the charger should be restarted externally.
  charger_modbus_communication_fault:
    name: "Error: charger Modbus communication fault"

  #Three booleans to mimic a radio button group for the charge mode the user can set in the UI
  chargemodeautomatic:
    name: ChargeModeAutomatic
    icon: mdi:battery-charging-80
    initial: true

  chargemodemaxboostnow:
    name: ChargeModeMaxBoostNow
    icon: mdi:battery-alert

  chargemodeoff:
    name: ChargeModeOff
    icon: mdi:battery-off

input_number:
  energy_price_vat:
    name: VAT
    min: 0
    max: 50
    step: 1
    mode: box
    unit_of_measurement: "%"

  energy_price_markup_per_kwh:
    name: Markup/kWh
    min: 0
    max: 200
    step: 0.001
    mode: box
    unit_of_measurement: ct/kWh

  charger_plus_car_roundtrip_efficiency:
    name: Roundtrip efficiency of charger and car
    min: 50
    max: 100
    step: 1
    icon: mdi:arrow-u-left-bottom
    mode: box
    unit_of_measurement: "%"

  charger_max_charging_power:
    name: Max charging power
    min: 1380
    max: 25000
    step: 1
    icon: mdi:car-arrow-left
    mode: box
    unit_of_measurement: W

  charger_max_discharging_power:
    name: " "
    min: 1380
    max: 25000
    step: 1
    icon: mdi:car-arrow-right
    mode: box
    unit_of_measurement: W

  charger_port:
    name: "Charger port"
    min: 1
    max: 65535
    step: 1
    icon: mdi:numeric
    mode: box
    unit_of_measurement: " "

  car_max_capacity_in_kwh:
    name: Car battery max. capacity
    min: 10
    max: 200
    step: 1
    icon: mdi:battery-high
    mode: box
    unit_of_measurement: kWh

  car_consumption_wh_per_km:
    name: Car energy consumption
    icon: mdi:gauge-low
    min: 100
    max: 400
    unit_of_measurement: Wh/km
    step: 1.0
    mode: box

  car_min_soc_in_percent:
    name: Car battery min. soc
    min: 10
    max: 30
    step: 1
    icon: mdi:chart-bell-curve-cumulative
    mode: box
    unit_of_measurement: "%"

  car_max_soc_in_percent:
    name: Car battery max. soc
    min: 60
    max: 95
    step: 1
    icon: mdi:chart-sankey
    mode: box
    unit_of_measurement: "%"

  allowed_duration_above_max_soc_in_hrs:
    name: Allowed duration above max soc
    min: 1
    max: 12
    step: 1
    icon: mdi:timer-lock-outline
    mode: box
    unit_of_measurement: "hrs"

  # Used in both UI and in code.
  car_state_of_charge:
    name: SoC history
    icon: mdi:battery-medium
    min: 0.0
    max: 100.0
    unit_of_measurement: "%"
    step: 1.0
    mode: slider

  # Used in both UI and in code.
  car_remaining_range:
    name: Car Remaining Range
    icon: mdi:ev-station
    min: 0
    max: 1000
    unit_of_measurement: "km"
    step: 100
    mode: box

  # Used for stats in UI.
  total_charging_cost_last_7_days:
    name: Total charging costs last 7 days
    max: 1000.00
    min: -1000.00
    step: 0.01
    unit_of_measurement: "€"
    mode: box

  # Used for stats in UI.
  total_charged_energy_last_7_days:
    name: Total charged energy last 7 days
    max: 10000
    min: -10000
    step: 1
    unit_of_measurement: "kWh"
    mode: box

  # Used for stats in UI.
  total_discharged_energy_last_7_days:
    name: Total discharged energy last 7 days
    max: 10000
    min: -10000
    step: 1
    unit_of_measurement: "kWh"
    mode: box

  # Used for stats in UI.
  net_energy_last_7_days:
    name: Total net energy last 7 days
    max: 10000
    min: -10000
    step: 1
    unit_of_measurement: "kWh"
    mode: box

  # Used for stats in UI.
  total_saved_emissions_last_7_days:
    name: Total saved emissions last 7 days
    max: 1000
    min: -1000
    step: 0.001
    unit_of_measurement: "kg CO2"
    mode: box

  # Used for stats in UI.
  total_emissions_last_7_days:
    name: Total emissions last 7 days
    max: 1000
    min: -1000
    step: 0.001
    unit_of_measurement: "kg CO2"
    mode: box

  # Used for stats in UI.
  net_emissions_last_7_days:
    name: Net emissions last 7 days
    max: 1000
    min: -1000
    step: 0.001
    unit_of_measurement: "kg CO2"
    mode: box


input_text:
  #############  calendar related entities #############
  calendar_account_init_url:
    name: Calendar host URL
    icon: mdi:web
  calendar_account_username:
    name: Username
    icon: mdi:account
  calendar_account_password:
    name: Password
    icon: mdi:form-textbox-password
    mode: password
  calendar_account_connection_status:
    mode: text
  # Util entity that holds the events in an attribute events
  calendar_events:
    mode: text

  #############  charger related entities #############
  charger_host_url:
    name: Charger host URL
    icon: mdi:lan-pending
  # This is not a setting but is read from the charger and is an upper limit for max_(dis-)charging_power
  charger_max_available_power:
    mode: text
    initial: "??"
  charger_connection_status:
    mode: text
  poll_refresh_indicator:
    name: This changes every time the EVSE gets polled (if active, 5 to 15 sec.)
    initial: " "
  # Used to show a user understandable version of the states in the UI.
  # "Translation" is done in an automation.
  charger_state:
    name: Charger state
    icon: mdi:ev-station
    max: 100
    mode: text
    min: 0


  #############  flexmeasures related entities #############
  fm_account_username:
    icon: mdi:account
    name: Username (email address)
  fm_account_password:
    icon: mdi:form-textbox-password
    name: Password
    mode: password
  fm_host_url:
    icon: mdi:server-network-outline
    name: URL
  fm_connection_status:
    mode: text

  ###################################################################
  #        self_provided settings related to au_amber_electric      #
  ###################################################################

  own_production_price_entity_id:
    icon: mdi:transmission-tower-import
    mode: text
    name: Source entity_id for self_provided production price
  own_consumption_price_entity_id:
    icon: mdi:transmission-tower-export
    mode: text
    name: Source entity_id for self_provided consumption price

  ###################################################################
  #        self_provided settings related to gb_octopus_energy      #
  ###################################################################

  octopus_import_code:
    icon: mdi:transmission-tower-import
    mode: text
    name: Octopus Electric import code

  octopus_export_code:
    icon: mdi:transmission-tower-export
    mode: text
    name: Octopus Electric export code

  octopus_region:
    icon: mdi:home-map-marker
    mode: text
    name: Octopus Electric region
    min: 1
    max: 1

  #############  UI statistics related entities #############
  total_discharge_time_last_7_days:
    name: Total discharge time in last 7 days
  total_charge_time_last_7_days:
    name: Total charge time in last 7 days

  # Helper, set by V2G Liberty.py based upon setting utility in secrets.
  # Used only for setting text in dashboard.
  utility_display_name:
    name: Utility display name
    icon: mdi:transmission-tower
    max: 100
    mode: text
    min: 0

  # Helper, set by V2G Liberty.py based upon setting fm_optimisation_mode in secrets.
  # Used only for setting text in dashboard.
  optimisation_mode:
    name: Optimisation mode
    icon: mdi:cog-transfer-outline
    max: 100
    mode: text
    min: 0

  # Used to store the (serialised) charge schedule HA receives from the
  # backend FM, not used in UI.
  chargeschedule:
    name: ChargeSchedule
    max: 10000
    min: 0
    mode: text
    icon: mdi:calendar-multiselect

  # Used to store the (serialized) list of dynamic consumption prices that is fetched by
  # get_fm_data code from FM. This then is shown in the UI in the graph.
  consumption_prices:
    name: Buy price
    max: 10000
    min: 0
    mode: text

  # Used to store the (serialized) list of dynamic consumption prices that is fetched by
  # get_fm_data code from FM. This then is shown in the UI in the graph.
  production_prices:
    name: Sell price
    max: 10000
    min: 0
    mode: text


  # Used to store the (serialized) list of hourly CO2 emissions that is fetched by
  # get_fm_data code from FM daily. This then is shown in the UI in the graph.
  co2_emissions:
    name: Emissions
    max: 10000
    min: 0
    mode: text

  # Based on the current SoC and the schedule a prognosis (list of values) is
  # calculated and this (serialised list) is stored in this variable. This is Used
  # in the graph, shown as yellow prognosis line.
  soc_prognosis:
    name: SoC schedule
    max: 10000
    mode: text
    min: 0

  # Based on the current SoC and max boost function (when SoC is below minimum).
  # This contains two values current SoC and min. SoC at expected time.
  # This is shown in the graph as a red prognosis line.
  soc_prognosis_boost:
    name: SoC Boost
    max: 10000
    mode: text
    min: 0

  # Based on the current SoC and Max Charge Now function (from the Charge Mode buttons).
  # This contains two values current SoC and 100%. SoC at expected time.
  # This is shown in the graph as a dashed prognosis line.
  soc_prognosis_max_charge_now:
    name: SoC Max Charge Now
    max: 10000
    mode: text
    min: 0

  # Forms bar representing the duration of the calendar item at
  # the desired %.
  calender_item_in_chart:
    name: Calendar item in chart
    max: 10000
    mode: text
    min: 0

  # Used for setting an error in the UI when V2G Liberty app cannot retrieve EPEX data.
  epex_log:
    name: epex_log
    max: 10000
    min: 0
    mode: text


script:
  restart_ha:
    alias: RestartHomeAssistant
    sequence:
      - event: RESTART_HA
        event_data: {}
    mode: single

  reset_to_factory_defaults:
    alias: ResetToFactoryDefaults
    sequence:
      - event: RESET_TO_FACTORY_DEFAULTS
        event_data: {}
    mode: single

  test_calendar_connection:
    alias: TestCalendarConnection
    sequence:
      - event: TEST_CALENDAR_CONNECTION
        event_data: {}
    mode: single

  test_charger_connection:
    alias: TestChargerConnection
    sequence:
      - event: TEST_CHARGER_CONNECTION
        event_data: {}
    mode: single

  test_fm_connection:
    alias: TestFMconnection
    sequence:
      - event: TEST_FM_CONNECTION
        event_data: {}
    mode: single

  disconnectnow:
    alias: DisconnectNow
    sequence:
      - event: DISCONNECT_CHARGER
        event_data: {}
    mode: single

  call_service_with_response:
    description: Calls a service and returns its response to AppDaemon
    fields:
      call_id:
        name: Call id
        default: 1
        description: An id to uniquely identify the call
        required: True
        selector:
          text:
      service_name:
        name: Service name
        default: domain.some_service
        description: The service to call
        required: True
        selector:
          text:
      service_data:
        name: Service data
        default: {}
        description: Data to pass to the service
        required: True
        selector:
          object:
    sequence:
      - service: "{{ service_name }}"
        data: "{{ service_data }}"
        response_variable: response
      - event: call_service_with_response.finished    # event name cannot be templated unfortunately
        event_data:
          call_id: "{{ call_id }}"
          response: "{{ response }}"

automation:
  - id: "1633010017995"
    alias: Chargemode to Automatic
    description: 'A bit of a hack because HA does not provide radiobuttons

      The values of the helper "input_select.charge_mode" are to be reflected in the
      UI as 3 (radio)buttons.

      Te give these buttons a on/off state for each of them a toggle helper is used.

      When a toggle-button is clicked an (these) automations receives the trigger selects
      the corresponding item in the input_select and switches the other toggles to off.'
    trigger:
      - platform: state
        entity_id: input_boolean.chargemodeautomatic
        from: "off"
        to: "on"
    condition: []
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.charge_mode
        data:
          option: Automatic
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.chargemodemaxboostnow
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.chargemodeoff
    mode: single
  - id: "1633010167089"
    alias: Chargemode to Max boost now
    description: 'A bit of a hack because HA does not provide radiobuttons

      The values of the helper "input_select.charge_mode" are to be reflected in the
      UI as 3 (radio)buttons.

      Te give these buttons a on/off state for each of them a toggle helper is used.

      When a toggle-button is clicked an (these) automations receives the trigger selects
      the corresponding item in the input_select and switches the other toggles to off.'
    trigger:
      - platform: state
        entity_id: input_boolean.chargemodemaxboostnow
        from: "off"
        to: "on"
    condition: []
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.charge_mode
        data:
          option: Max boost now
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.chargemodeautomatic
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.chargemodeoff
    mode: single
  - id: "1633010384766"
    alias: Chargemode to Off
    description: 'A bit of a hack because HA does not provide radiobuttons

      The values of the helper "input_select.charge_mode" are to be reflected in the
      UI as 3 (radio)buttons.

      Te give these buttons a on/off state for each of them a toggle helper is used.

      When a toggle-button is clicked an (these) automations receives the trigger selects
      the corresponding item in the input_select and switches the other toggles to off.'
    trigger:
      - platform: state
        entity_id: input_boolean.chargemodeoff
        from: "off"
        to: "on"
    condition: []
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.charge_mode
        data:
          option: Stop
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.chargemodeautomatic
        data: {}
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.chargemodemaxboostnow
        data: {}
    mode: single
